// <auto-generated />
using System;
using BookRentalObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookRentalObject.Migrations
{
    [DbContext(typeof(BookRentalDBContext))]
    [Migration("20260404175741_SyncDocuTable")]
    partial class SyncDocuTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookRentalObject.AuditTrail", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("auditId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"), 1L, 1);

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("newValue");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("oldValue");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("AuditId")
                        .HasName("PK_AUDIT_TRAILS");

                    b.HasIndex("UserId");

                    b.ToTable("Audit Trails");
                });

            modelBuilder.Entity("BookRentalObject.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("authorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastName");

                    b.HasKey("AuthorId");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("BookRentalObject.AvailabilityStatus", b =>
                {
                    b.Property<int>("AvailabiltyStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("availabiltyStatusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabiltyStatusId"), 1L, 1);

                    b.Property<string>("AvailabilityStatus1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("availabilityStatus");

                    b.HasKey("AvailabiltyStatusId");

                    b.ToTable("Availability Status");
                });

            modelBuilder.Entity("BookRentalObject.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bookId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("authorId");

                    b.Property<int>("AvailabilityStatusId")
                        .HasColumnType("int")
                        .HasColumnName("availabilityStatusId");

                    b.Property<int>("BookConditionId")
                        .HasColumnType("int")
                        .HasColumnName("bookConditionId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int")
                        .HasColumnName("imageID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime")
                        .HasColumnName("publishDate");

                    b.Property<double>("RentalPrice")
                        .HasColumnType("float")
                        .HasColumnName("rentalPrice");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("AvailabilityStatusId");

                    b.HasIndex("BookConditionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BookRentalObject.BookCondition", b =>
                {
                    b.Property<int>("BookConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bookConditionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookConditionId"), 1L, 1);

                    b.Property<string>("ReturnCondition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("returnCondition");

                    b.HasKey("BookConditionId");

                    b.ToTable("Book Condition");
                });

            modelBuilder.Entity("BookRentalObject.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("categoryName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("BookRentalObject.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("documentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"), 1L, 1);

                    b.Property<byte[]>("Blob")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("BLOB");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fileName");

                    b.Property<int>("RentalRequestId")
                        .HasColumnType("int")
                        .HasColumnName("rentalRequestId");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime")
                        .HasColumnName("uploadDate");

                    b.HasKey("DocumentId");

                    b.HasIndex("RentalRequestId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("BookRentalObject.ExtraCharge", b =>
                {
                    b.Property<int>("ExtraChargesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("extraChargesId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtraChargesId"), 1L, 1);

                    b.Property<string>("ExtraChargeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("extra_charge_name");

                    b.Property<double>("ExtraChargeRate")
                        .HasColumnType("float")
                        .HasColumnName("Extra_charge_rate");

                    b.HasKey("ExtraChargesId");

                    b.ToTable("Extra Charges");
                });

            modelBuilder.Entity("BookRentalObject.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedbackId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("bookId");

                    b.Property<string>("Comment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("comment");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("isHidden");

                    b.Property<int>("Rate")
                        .HasColumnType("int")
                        .HasColumnName("rate");

                    b.Property<int?>("ReturnRecordId")
                        .HasColumnType("int")
                        .HasColumnName("returnRecordId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("FeedbackId");

                    b.HasIndex("BookId");

                    b.HasIndex("ReturnRecordId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("BookRentalObject.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("imageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"), 1L, 1);

                    b.Property<byte[]>("Blob")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("BLOB");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imageName");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imageType");

                    b.HasKey("ImageId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("BookRentalObject.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("logId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"), 1L, 1);

                    b.Property<string>("AffectedData")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("affectedData");

                    b.Property<string>("Exceptions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("exceptions");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("BookRentalObject.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"), 1L, 1);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("message");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subject");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("BookRentalObject.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentMethodId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"), 1L, 1);

                    b.Property<string>("PaymentMethod1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paymentMethod");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("Payment Method");
                });

            modelBuilder.Entity("BookRentalObject.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"), 1L, 1);

                    b.Property<string>("PaymentStatus1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paymentStatus");

                    b.HasKey("PaymentId");

                    b.ToTable("Payment Status");
                });

            modelBuilder.Entity("BookRentalObject.RentalRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("requestId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("bookId");

                    b.Property<int>("RentalRequestStatusId")
                        .HasColumnType("int")
                        .HasColumnName("rentalRequestStatusId");

                    b.Property<DateTime>("RentalStartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("rentalStartDate");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime")
                        .HasColumnName("returnDate");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float")
                        .HasColumnName("totalCost");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("RequestId");

                    b.HasIndex("BookId");

                    b.HasIndex("RentalRequestStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Rental Request");
                });

            modelBuilder.Entity("BookRentalObject.RentalRequestStatus", b =>
                {
                    b.Property<int>("RentalRequestStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rentalRequestStatusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalRequestStatusId"), 1L, 1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("RentalRequestStatusId");

                    b.ToTable("Rental Request Status");
                });

            modelBuilder.Entity("BookRentalObject.RentalTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("bookId");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit")
                        .HasColumnName("isReturned");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("paymentMethodId");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("paymentStatusId");

                    b.Property<double>("RentalFee")
                        .HasColumnType("float")
                        .HasColumnName("rentalFee");

                    b.Property<int>("RentalPeriod")
                        .HasColumnType("int")
                        .HasColumnName("rentalPeriod");

                    b.Property<int>("RentalRequestId")
                        .HasColumnType("int")
                        .HasColumnName("rentalRequestId");

                    b.Property<DateTime>("RentalStartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("rentalStartDate");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime")
                        .HasColumnName("returnDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("TransactionId");

                    b.HasIndex("BookId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Rental Transaction");
                });

            modelBuilder.Entity("BookRentalObject.ReturnRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"), 1L, 1);

                    b.Property<DateTime>("ActualReturnDate")
                        .HasColumnType("datetime")
                        .HasColumnName("actualReturnDate");

                    b.Property<int>("BookConditionId")
                        .HasColumnType("int")
                        .HasColumnName("bookConditionId");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("bookId");

                    b.Property<DateTime>("ExpectedReturnDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expectedReturnDate");

                    b.Property<int?>("ExtraChargesId")
                        .HasColumnType("int")
                        .HasColumnName("extraChargesId");

                    b.Property<double>("LateReturnFee")
                        .HasColumnType("float")
                        .HasColumnName("lateReturnFee");

                    b.Property<double>("TotalAdditionalCharges")
                        .HasColumnType("float")
                        .HasColumnName("totalAdditionalCharges");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transactionId");

                    b.HasKey("RecordId");

                    b.HasIndex("BookConditionId");

                    b.HasIndex("BookId");

                    b.HasIndex("ExtraChargesId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Return Records");
                });

            modelBuilder.Entity("BookRentalObject.Suggestion", b =>
                {
                    b.Property<int>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("suggestionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionId"), 1L, 1);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("subject");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("SuggestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Suggestion");
                });

            modelBuilder.Entity("BookRentalObject.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("ContactNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("contactNo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastName");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int")
                        .HasColumnName("userRoleId");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BookRentalObject.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userRoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"), 1L, 1);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.HasKey("UserRoleId");

                    b.ToTable("User Role");
                });

            modelBuilder.Entity("BookRentalObject.AuditTrail", b =>
                {
                    b.HasOne("BookRentalObject.User", "User")
                        .WithMany("AuditTrails")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AUDIT_TRAILS_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookRentalObject.Book", b =>
                {
                    b.HasOne("BookRentalObject.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Book_Author");

                    b.HasOne("BookRentalObject.AvailabilityStatus", "AvailabilityStatus")
                        .WithMany("Books")
                        .HasForeignKey("AvailabilityStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Book_Availability Status");

                    b.HasOne("BookRentalObject.BookCondition", "BookCondition")
                        .WithMany("Books")
                        .HasForeignKey("BookConditionId")
                        .IsRequired()
                        .HasConstraintName("FK_Equipment_Equipment Condition");

                    b.HasOne("BookRentalObject.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Book_Category");

                    b.HasOne("BookRentalObject.Image", "Image")
                        .WithMany("Books")
                        .HasForeignKey("ImageId")
                        .HasConstraintName("FK_Book_Image");

                    b.Navigation("Author");

                    b.Navigation("AvailabilityStatus");

                    b.Navigation("BookCondition");

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("BookRentalObject.Document", b =>
                {
                    b.HasOne("BookRentalObject.RentalRequest", "RentalRequest")
                        .WithMany("Documents")
                        .HasForeignKey("RentalRequestId")
                        .IsRequired()
                        .HasConstraintName("FK_Document_RentalRequest2");

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("BookRentalObject.Feedback", b =>
                {
                    b.HasOne("BookRentalObject.Book", "Book")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Book");

                    b.HasOne("BookRentalObject.ReturnRecord", "ReturnRecord")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ReturnRecordId")
                        .HasConstraintName("FK_Feedback_ReturnRecords");

                    b.Navigation("Book");

                    b.Navigation("ReturnRecord");
                });

            modelBuilder.Entity("BookRentalObject.Log", b =>
                {
                    b.HasOne("BookRentalObject.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Log_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookRentalObject.Notification", b =>
                {
                    b.HasOne("BookRentalObject.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookRentalObject.RentalRequest", b =>
                {
                    b.HasOne("BookRentalObject.Book", "Book")
                        .WithMany("RentalRequests")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_Rental Request_Equipment");

                    b.HasOne("BookRentalObject.RentalRequestStatus", "RentalRequestStatus")
                        .WithMany("RentalRequests")
                        .HasForeignKey("RentalRequestStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Rental Request_Rental Request Status");

                    b.HasOne("BookRentalObject.User", "User")
                        .WithMany("RentalRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Rental Request_User");

                    b.Navigation("Book");

                    b.Navigation("RentalRequestStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookRentalObject.RentalTransaction", b =>
                {
                    b.HasOne("BookRentalObject.Book", "Book")
                        .WithMany("RentalTransactions")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_Rental Transaction_Book");

                    b.HasOne("BookRentalObject.PaymentMethod", "PaymentMethod")
                        .WithMany("RentalTransactions")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_Rental Transaction_Payment Method");

                    b.HasOne("BookRentalObject.PaymentStatus", "PaymentStatus")
                        .WithMany("RentalTransactions")
                        .HasForeignKey("PaymentStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Rental Transaction_Payment Status");

                    b.HasOne("BookRentalObject.User", "User")
                        .WithMany("RentalTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Rental Transaction_User");

                    b.Navigation("Book");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookRentalObject.ReturnRecord", b =>
                {
                    b.HasOne("BookRentalObject.BookCondition", "BookCondition")
                        .WithMany("ReturnRecords")
                        .HasForeignKey("BookConditionId")
                        .IsRequired()
                        .HasConstraintName("FK_Return Records_Equipment Condition");

                    b.HasOne("BookRentalObject.Book", "Book")
                        .WithMany("ReturnRecords")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_Return Records_Equipment");

                    b.HasOne("BookRentalObject.ExtraCharge", "ExtraCharges")
                        .WithMany("ReturnRecords")
                        .HasForeignKey("ExtraChargesId")
                        .HasConstraintName("FK_Return Records_Extra Charges");

                    b.HasOne("BookRentalObject.RentalTransaction", "Transaction")
                        .WithMany("ReturnRecords")
                        .HasForeignKey("TransactionId")
                        .IsRequired()
                        .HasConstraintName("FK_Return Records_Rental Transaction");

                    b.Navigation("Book");

                    b.Navigation("BookCondition");

                    b.Navigation("ExtraCharges");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BookRentalObject.Suggestion", b =>
                {
                    b.HasOne("BookRentalObject.User", "User")
                        .WithMany("Suggestions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Suggestion_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookRentalObject.User", b =>
                {
                    b.HasOne("BookRentalObject.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_User Role");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("BookRentalObject.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookRentalObject.AvailabilityStatus", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookRentalObject.Book", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("RentalRequests");

                    b.Navigation("RentalTransactions");

                    b.Navigation("ReturnRecords");
                });

            modelBuilder.Entity("BookRentalObject.BookCondition", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("ReturnRecords");
                });

            modelBuilder.Entity("BookRentalObject.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookRentalObject.ExtraCharge", b =>
                {
                    b.Navigation("ReturnRecords");
                });

            modelBuilder.Entity("BookRentalObject.Image", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookRentalObject.PaymentMethod", b =>
                {
                    b.Navigation("RentalTransactions");
                });

            modelBuilder.Entity("BookRentalObject.PaymentStatus", b =>
                {
                    b.Navigation("RentalTransactions");
                });

            modelBuilder.Entity("BookRentalObject.RentalRequest", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BookRentalObject.RentalRequestStatus", b =>
                {
                    b.Navigation("RentalRequests");
                });

            modelBuilder.Entity("BookRentalObject.RentalTransaction", b =>
                {
                    b.Navigation("ReturnRecords");
                });

            modelBuilder.Entity("BookRentalObject.ReturnRecord", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("BookRentalObject.User", b =>
                {
                    b.Navigation("AuditTrails");

                    b.Navigation("Logs");

                    b.Navigation("Notifications");

                    b.Navigation("RentalRequests");

                    b.Navigation("RentalTransactions");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("BookRentalObject.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
